package ua.sakharevich.db.pojo;

import java.io.Serializable;

public class User implements java.io.Serializable {
	
	private String email;
	private String password;
	private String autoGeneratedLogin;
	private  int autoGeneratedID;
	private String profile; 
	
	
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getAutoGeneratedLogin() {
		return autoGeneratedLogin;
	}
	public void setAutoGeneratedLogin(String autoGeneratedLogin) {
		this.autoGeneratedLogin = autoGeneratedLogin;
	}
	public int getAutoGeneratedID() {
		return autoGeneratedID;
	}
	public void setAutoGeneratedID(int autoGeneratedID) {
		this.autoGeneratedID = autoGeneratedID;
	}
	public String getProfile() {
		return profile;
	}
	public void setProfile(String profile) {
		this.profile = profile;
	}
	@Override
	public String toString() {
		return "User [email=" + email + ", password=" + password
				+ ", autoGeneratedLogin=" + autoGeneratedLogin
				+ ", autoGeneratedID=" + autoGeneratedID + ", profile="
				+ profile + "]";
	}
	
	
	

	

}
