package ua.sakharevich.db.mysql;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

import ua.sakharevich.db.pojo.User;
import ua.sakharevich.db.dao.*;

public class MysqlUserDAO implements UserDAO {

	private Connection connection;
	User user = new User();



	public MysqlUserDAO(Connection connection) {
		this.connection = connection;
	}




	@Override
	public User createUser() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public User readUser(int key) throws SQLException {	
		

		
		//create sql statement
		String sql = "SELECT * FROM users.user WHERE id = ?;";
		
		PreparedStatement stm = connection.prepareStatement(sql);
		
		// set key on first "?"
		stm.setInt(1, key); 
		
		ResultSet rs = stm.executeQuery(); 
		
		rs.next(); 
		user.setEmail(rs.getString("email"));
		user.setPassword(rs.getString("password"));
		user.setAutoGeneratedLogin(rs.getString("login"));
		user.setAutoGeneratedID(rs.getInt("id"));
		user.setProfile(rs.getString("profile"));
		
		return user;
	}

	@Override
	public boolean updateUser(User user) {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public boolean deleteUser(User user) {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public List<User> allUsers() throws SQLException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public String toString() {
		return this.user.toString();
	}

}
